### ISSUE TITLE
[FeatureRequest] Apply this rule on import declarations

### ISSUE THREAD

**Issue by bertho-zero** [urielvan/eslint-plugin-newline-destructuring#10]
Thanks for this rule, it would be great if it could be applied in the same way to import/export declarations and object literals.

By taking a config similar to https://eslint.style/rules/js/object-curly-newline, for example:

```js
    'newline-destructuring/newline': [
      'error',
      {
        ObjectExpression: {
          items: 4,
          itemsWithRest: 4,
          maxLength: 60,
          consistent: true,
        },
        ObjectPattern: {
          items: 4,
          itemsWithRest: 4,
          maxLength: 60,
          consistent: true,
        },
        ImportDeclaration: {
          items: 4,
          itemsWithRest: 4,
          maxLength: 60,
          consistent: true,
        },
        ExportDeclaration: {
          items: 4,
          itemsWithRest: 4,
          maxLength: 60,
          consistent: true,
        },
      },
    ],
```

![image](https://github.com/user-attachments/assets/f10127bf-e87d-46a6-bcda-875c875a27d5)

**Comment by urielvan** [comment]
Thank you for compliment. However, my original intention in writing this plugin was to specifically address issues related to object destructuring, and I don't plan to expand the rule's application scenarios too broadly.

Extending the formatting to these scenarios is likely to cause some uncertain conflicts with other preset rule sets. Additionally, the scenarios you mentioned already have existing rules:

- Object literals [eslint official](https://eslint.org/docs/latest/rules/object-curly-newline)
- Import declarations [eslint-plugin-import-newlines](https://github.com/SeinopSys/eslint-plugin-import-newlines), which I personally use and highly recommend
- Export declarations [eslint-plugin-canonical](https://github.com/gajus/eslint-plugin-canonical?tab=readme-ov-file#eslint-plugin-canonical-rules-export-specifier-newline), which I haven't used myself but it seems to address your concerns

I hope these three suggestions can help you solve the problem.

**Comment by bertho-zero** [comment]
Thanks for your reply and the resources.

> Object literals [eslint official](https://eslint.org/docs/latest/rules/object-curly-newline)

This rule (`object-curly-newline`) just allows to add spaces after `{` and before `}`, and the [`object-property-newline`](https://eslint.style/rules/js/object-property-newline) rule is not as flexible as this plugin.

> Import declarations [eslint-plugin-import-newlines](https://github.com/SeinopSys/eslint-plugin-import-newlines), which I personally use and highly recommend

This plugin seems good and does pretty much the same thing as this one but for imports. :+1: 

> Export declarations [eslint-plugin-canonical](https://github.com/gajus/eslint-plugin-canonical?tab=readme-ov-file#eslint-plugin-canonical-rules-export-specifier-newline), which I haven't used myself but it seems to address your concerns

This is not flexible, it's all or nothing.
