### ISSUE TITLE
Allow props under the `items` limit to be on new lines

### ISSUE THREAD

**Issue by dhensby** [urielvan/eslint-plugin-newline-destructuring#3]
The `items` option is described as:

>Specifies the maximum number of properties before the plugin requires breaking up the statement to multiple lines.

This implies that the rule is agnostic to whether props under the `items` limit are on new lines or not, however it seems to be forcing these props to be on the same line.

For example:

```json
{
  ...
  "rules": {
    "newline-destructuring/newline": ["error", { items: 3 }],
    ...
  }
}
```

```js
const {
  a,
  b,
  c,
} = x;
```

Results in a linting error and the rule enforces the syntax to be:

```js
const { a, b , c } = x;
```

Is it possible to have an option for the rule to not be opinionated about this so that either is allowed?

**Comment by urielvan** [comment]
It seems that I made quite a mistake when writing the doc. 😢
I've updated it.

**Comment by dhensby** [comment]
Thanks for updating the docs. Would you be willing to accept a PR which added a feature allowing a number items under these limits to be on new lines? Do you have an opinion on the name of this setting if so?

**Comment by urielvan** [comment]
A PR is welcomed, of course.
But frankly, I'm still confusing how you want the code to be formatted. 😵

For example,
```
{
  "rules": {
    "newline-destructuring/newline": ["error", { items: 5, someNewOption: 3 }]
  }
}
```
When there are 3 properties or less, you want it to be on new lines. When there 4 or 5, they are on same line, and when there are more than 5, they are moved to new lines?

**Comment by dhensby** [comment]
@urielvan I've just authored the PR, so maybe that makes it clearer?

I essentially just want to allow properties to be on new lines all the time but to only be *enforced* when there are more than 3 properties.

Or, conversely, always enforce new lines but not for less than 3 props (in which case either inline or all on separate lines is fine).

**Comment by dhensby** [comment]
@urielvan - thanks for the prompt review and merge.

Unfortunately it looks like v1.1.0 has been published to the registry without the source being compiled/built - so the new option isn't actually available.

I've opened #5 to add the `prepack` script to the `package.json` file so hopefully that won't happen again.

Would you mind pushing a 1.1.1 release with the built files? 🙏

**Comment by urielvan** [comment]
OMG...
Thanks a lot.

**Comment by dhensby** [comment]
v1.1.1 is working 🎉

**Comment by urielvan** [comment]
I've learnt a lot about github workflow and npm scripts from your PRs.
Thank you. 😊
