### ISSUE TITLE
feature suggestion - option to disable force to use single line

### ISSUE THREAD

**Issue by nerijussavickas** [urielvan/eslint-plugin-newline-destructuring#6]
Hi,
is it possible to ask for a feature - forceSingleLine (true/false) - enable/disable force to use use a single line when the number of properties hasn't reached `items`?

**Comment by urielvan** [comment]
Maybe `consistent` is what you need？
You may check #3

**Comment by nerijussavickas** [comment]
YES, exactly! Thanks so much!
