### ISSUE TITLE
Consistent option doesn't work as expected

### ISSUE THREAD

**Issue by hrubysi** [urielvan/eslint-plugin-newline-destructuring#7]
I would expect similar behavior as in `object-property-newline`.
I might be misunderstanding `consistent` option, but I don't see any difference between `true` and `false` in the following case:

### Steps to reproduce

**Code snippet**
```
const object = {
  a: 1,
  b: 2, c: 3,
};
const {
  a,
  b, c,
} = object;
```

**Eslint fix result**

```
const object = {
  a: 1,
  b: 2,
  c: 3,
};
const {a, b, c} = object;
```

**Expected result**

```
const object = {
  a: 1,
  b: 2,
  c: 3,
};
const {
  a,
  b,
  c,
} = object;
```

### Rules options

```
{
    'object-property-newline': [
      'error',
      {allowAllPropertiesOnSameLine: true},
    ],
    'newline-destructuring/newline': ['error', {
      consistent: true,
      items: 3,
    }],
  }
```

**Comment by urielvan** [comment]
It seems that you may confuse [object initializer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) and [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). This plugin only take care of the latter.

About the consitent option, it is designed to work so. Here is the [original description](https://github.com/urielvan/eslint-plugin-newline-destructuring/issues/3#issuecomment-1297094825)

**Comment by hrubysi** [comment]
I understand the difference, object initializer in the example is handled by `object-property-newline` and I wanted to achieve the same behavior with destructuring.

What I meant is, if length of items is less than `n`, all items can be on the same line, but if some isn't, they should all go on a new line. 

However, maybe it's out of scope of this plugin.

**Comment by urielvan** [comment]
I add a new option `allowAllPropertiesOnSameLine` in the new release.

Although I add some tests, but I'm not quite confident whether it will work fine with the consistent option. So a new issue is welcomed if you run into some strange cases.
